/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/estoque/': RouteRecordInfo<'/estoque/', '/estoque', Record<never, never>, Record<never, never>>,
    '/medicamentos/': RouteRecordInfo<'/medicamentos/', '/medicamentos', Record<never, never>, Record<never, never>>,
    '/registrar-entrada/': RouteRecordInfo<'/registrar-entrada/', '/registrar-entrada', Record<never, never>, Record<never, never>>,
    '/registrar-saida/': RouteRecordInfo<'/registrar-saida/', '/registrar-saida', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/pages/estoque/index.vue': {
      routes: '/estoque/'
      views: never
    }
    'src/pages/medicamentos/index.vue': {
      routes: '/medicamentos/'
      views: never
    }
    'src/pages/registrar-entrada/index.vue': {
      routes: '/registrar-entrada/'
      views: never
    }
    'src/pages/registrar-saida/index.vue': {
      routes: '/registrar-saida/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
